basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name = 'relative'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^user_login/$', views.user_login, name = 'user_login'),
    url(r'^other/$', views.other, name='other'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name = 'index'),
    url(r'^basic_app/', include('basic_app.urls')), # carrot says anything that goes before and then basic_app
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name = 'special'),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required




# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)



def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()





    return render(request, 'basic_app/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})
@login_required
def special(request):
    return HttpResponse("You are logged in.")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username') #use same names as html file
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html',{})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </head>
  <body>

    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class = "navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">BRAND</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'admin:index' %}">ADMIN</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">REGISTER</a> </li>
          <li> <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">OTHER</a> </li>

          {% if user.is_authenticated %}
          <li> <a class='nav-item nav-link' href="{% url 'logout' %}">Logout</a> </li>
          {% else %}
          <li> <a class='nav-item nav-link' href="{% url 'basic_app:user_login'%}">Login</a> </li>
          {% endif %}
        </ul>

      </div>

    </nav>
    <div class="container">

      {% block body_block %}
      <!-- anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>



  </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{% load my_extras %}
  {% block body_block %}
  <div class="jumbotron">

    <h1>django level 5</h1>
    <h1>Welcome to index!</h1>
    <h1>this is index.html page showing!</h1>
    <h1>{{ text|upper }}</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>

    </div>
{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login:</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>welcome to other!</h1>
    <h2>this is an example of template inheritance</h2>
    {% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>thank you for registering!</h1>
  {% else %}
  <h1>Register here!</h1>
  <h3>Fill out the form:</h3>

  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">

  </form>

  {% endif %}

</div>



{% endblock %}

templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <h1>welcome to URL templates!</h1>
    <div class="container">
      <div class="jumbotron">
        <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
        <p></p>
        <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
        <p></p>
        <a href="{% url 'index' %}">LINK TO INDEX</a>

      </div>

    </div>



  </body>
</html>